project:
  type: book

book:
  title: "Bioinformatics Documentation"
  chapters:
    - index.qmd
    - part: "Saga and NIRD usage"
      chapters:
      - quarto_files/part_saga_nird/account_saga.qmd
    - part: "Part_2"
      chapters:
      - quarto_files/Part_2/dummy_document_2.qmd
    - quarto_files/contributing.qmd

format:
  html:
    theme: cosmo

editor: visual
