# Preface {.unnumbered}

This site contains the bioinformatics related documentation at the NVI.

To learn more about Quarto books visit <https://quarto.org/docs/books>.

This quarto book contains the following:

## Lab rules

1.  [Lab rules](quarto_files/labrules/labrules.qmd)

## Systems overview

1.  [Data production](quarto_files/part_configrations/setting_home_dir.qmd)
2.  [Chb](quarto_files/part_configrations/connecting_r_studio_to_github.qmd)

## External tutorials

1. [External tutorials](quarto_files/part_external/external_tutorials.qmd)
1. [Carpentriesh Unix shell lesson]
2. [Carpentries R tutorial]
3. [Incubator lesson]
4. [Carpentries metagenomics]
5. [Regex tutorial]
6. [Sigma2 documentation]

## Saga and NIRD usage

1. [Account on Saga/NIRD](quarto_files/part_saga_nird/account_saga.qmd)
2. [Saga and NIRD data architecture][quarto_files/part_saga_nird/data_architecture.qmd]
3. [First time on Saga]][quarto_files/part_saga_nird/first_time.qmd]
4. [Logging in to Saga/NIRD]][quarto_files/part_saga_nird/login.qmd]


## VIGAS usage







